import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/* ===== helpers ===== */

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/* ===== EXAM HTML ===== */

function buildExamHtml(questions: any[]) {
  let html = `
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8" />
<style>
  body {
    font-family: "Times New Roman", serif;
    margin: 40px 50px;
    line-height: 1.7;
    color: #000;
  }

  h1 {
    text-align: center;
    margin-bottom: 40px;
  }

  .question {
    margin-bottom: 24px;
  }

  .question-title {
    font-weight: bold;
    margin-bottom: 10px;
  }

  .choice {
    margin-right: 20px;
    margin-bottom: 4px;
  }

  .footer {
    position: fixed;
    bottom: 18px;
    left: 0;
    right: 0;
    text-align: center;
    font-size: 10px;
    color: #999;
    letter-spacing: 0.2px;
  }
</style>
</head>
<body>

<h1>امتحان QCM</h1>
`;

  questions.forEach((q, i) => {
    html += `
<div class="question">
  <div class="question-title">
    ${i + 1}. ${escapeHtml(q.question)}
  </div>
`;

    q.choices.forEach((c: string, j: number) => {
      html += `
  <div class="choice">
    ${String.fromCharCode(65 + j)}. ${escapeHtml(c)}
  </div>
`;
    });

    html += `</div>`;
  });

  html += `
<div class="footer">
  Generated by ExamForge
</div>

</body>
</html>
`;

  return html;
}

/* ===== CORRECTION HTML ===== */

function buildCorrectionHtml(questions: any[]) {
  let html = `
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8" />
<style>
  body {
    font-family: "Times New Roman", serif;
    margin: 40px 50px;
    line-height: 1.7;
    color: #000;
  }

  h1 {
    text-align: center;
    margin-bottom: 40px;
  }

  .question {
    margin-bottom: 26px;
  }

  .question-title {
    font-weight: bold;
    margin-bottom: 6px;
  }

  .answer {
    margin-right: 24px;
    color: #1f5c3a;
    font-weight: bold;
  }

  .footer {
    position: fixed;
    bottom: 18px;
    left: 0;
    right: 0;
    text-align: center;
    font-size: 10px;
    color: #999;
    letter-spacing: 0.2px;
  }
</style>
</head>
<body>

<h1>تصحيح امتحان QCM</h1>
`;

  questions.forEach((q, i) => {
    let answer = "—";

    if (typeof q.correctIndex === "number") {
      answer = String.fromCharCode(65 + q.correctIndex);
    } else if (Array.isArray(q.correctIndex)) {
      answer = q.correctIndex
        .map((n: number) => String.fromCharCode(65 + n))
        .join(", ");
    }

    html += `
<div class="question">
  <div class="question-title">
    ${i + 1}. ${escapeHtml(q.question)}
  </div>
  <div class="answer">
    ✔ ${answer}
  </div>
</div>
`;
  });

  html += `
<div class="footer">
  Generated by ExamForge
</div>

</body>
</html>
`;

  return html;
}

/* ===== ROUTE ===== */

export async function POST(req: Request) {
  try {
    const { questions } = await req.json();

    if (!Array.isArray(questions) || questions.length === 0) {
      return NextResponse.json(
        { status: "ERROR", message: "QUESTIONS_INVALIDES" },
        { status: 400 }
      );
    }

    const examHtml = buildExamHtml(questions);
    const correctionHtml = buildCorrectionHtml(questions);

    // ⚠️ V0 : on NE GÉNÈRE PAS de PDF côté serveur (Vercel-safe)
    // On retourne le HTML brut

    return NextResponse.json({
      status: "OK",
      examHtml,
      correctionHtml,
    });
  } catch (e: any) {
    return NextResponse.json(
      { status: "ERROR", message: e?.message || "GENERATION_FAILED" },
      { status: 500 }
    );
  }
}
